### ISSUE TITLE
Questioning loading yesterday in the history page by default

### ISSUE THREAD

**Issue by snikch** [balloob/home-assistant-js#21]
It seems to make more sense to me to load the current date, rather than yesterday, in the history view.

I was wondering if there's a reasoning behind this decision that I'm missing?

https://github.com/home-assistant/home-assistant-js/blob/master/src/modules/entity-history/stores/current-entity-history-date-store.js#L9

Cheers

**Comment by snikch** [comment]
(I did have a look in the issues to see if this had been discussed, sorry if I missed it)

**Comment by justweb1** [comment]
It looks like that call is to set the range of the history on the more-infos card history. This does not seem to be an actual issue. Please ask questions like this on the forum or in the chat. https://home-assistant.io/help
