### ISSUE TITLE
Clearing authToken on first failure

### ISSUE THREAD

**Issue by glance-** [balloob/home-assistant-js#24]
I think its pretty harsh to clear the authToken on first failure.

Its quite common for me to see different errors, due to configuration error, network error, bugs or any other reason. To clear authToken on first failure seems a bit harsh. I would like to see the js code to keep it even when there is failures in communication with the backend.

**Comment by balloob** [comment]
Fixed in https://github.com/home-assistant/home-assistant-polymer/pull/180
