### ISSUE TITLE
Private Browsing is not supported

### ISSUE THREAD

**Issue by rmkraus** [balloob/home-assistant-js#8]
In at least iOS, private browsing seems to cause this to crash. The error appears to be here:

https://github.com/balloob/home-assistant-js/blob/master/src/modules/preferences/localstorage-preferences.js#L5

It seems that iOS Safari will return a localStorage object, but throw errors when writing to it is attempted.

**Comment by balloob** [comment]
To check if it is supported we should use this fix:
http://stackoverflow.com/a/14555361/646416

On Thu, Jan 14, 2016 at 9:16 AM, Ryan Kraus notifications@github.com
wrote:

> In at least iOS, private browsing seems to cause this to crash. The error
> appears to be here:
> 
> https://github.com/balloob/home-assistant-js/blob/master/src/modules/preferences/localstorage-preferences.js#L5
> 
> It seems that iOS Safari will return a localStorage object, but throw
> errors when writing to it is attempted.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/balloob/home-assistant-js/issues/8.

## 

PaulusSchoutsen.nl
It's nice to be important but it's more important to be nice.

**Comment by balloob** [comment]
Fixed 311b89f640faf717b795379a8ad62ce951c548cd
