### ISSUE TITLE
lastUpdated is needed to graph correctly

### ISSUE THREAD

**Issue by sdague** [balloob/home-assistant-js#9]
The JS model only creates lastChanged attribute on all the entities. lastChanged is as the x axis for all the time series graphs.

This means that even if we expose all the event history for a thermostat, we won't get the line graphs we are expecting, as what we'll actually get is all the temperature changes stacked up at 1 x value, and then a jump to the next state change on the thermostat.

This looks like it will need changes in the polymer and js code to be supported before changing the python code to add domains will have an impact.

**Comment by sdague** [comment]
Related to https://github.com/balloob/home-assistant/issues/881

**Comment by balloob** [comment]
[This is the file that needs updating, the data is already there](https://github.com/balloob/home-assistant-js/blob/master/src/modules/entity/model.js)

**Comment by sdague** [comment]
https://github.com/balloob/home-assistant-js/pull/10 closed this issue
